# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "yahoo_sports19"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chetan Sarva"]
  s.date = "2012-10-21"
  s.description = "Ruby library for parsing stats from Yahoo! Sports pages. Currently supports MLB, NBA, NFL and NHL stats and info."
  s.email = "chetan@pixelcop.net"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "Manifest.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/yahoo_sports.rb",
    "lib/yahoo_sports/base.rb",
    "lib/yahoo_sports/mlb.rb",
    "lib/yahoo_sports/nba.rb",
    "lib/yahoo_sports/nfl.rb",
    "lib/yahoo_sports/nhl.rb",
    "test/test_helper.rb",
    "test/test_yahoo_sports.rb",
    "test/yahoo_sports/test_base.rb",
    "test/yahoo_sports/test_mlb.rb",
    "test/yahoo_sports/test_nba.rb",
    "test/yahoo_sports/test_nfl.rb",
    "test/yahoo_sports/test_nhl.rb",
    "yahoo_sports.gemspec"
  ]
  s.homepage = "http://github.com/chetan/yahoo_sports"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby library for parsing stats from Yahoo! Sports pages"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<scrapi>, ["~> 2.0"])
      s.add_runtime_dependency(%q<tzinfo>, ["~> 0.3.15"])
      s.add_runtime_dependency(%q<htmlentities>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<turn>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<scrapi>, ["~> 2.0"])
      s.add_dependency(%q<tzinfo>, ["~> 0.3.15"])
      s.add_dependency(%q<htmlentities>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<turn>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<scrapi>, ["~> 2.0"])
    s.add_dependency(%q<tzinfo>, ["~> 0.3.15"])
    s.add_dependency(%q<htmlentities>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<turn>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

